# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : Matan-h
title_separator          : "-"
subtitle                 : 
name                     : &name "matan-h" # &name is a YAML anchor which can be *referenced later
description              : &description "my blog"
#url                      : https://matan-h.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url                      : "https://matan-h.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : '' # the subpath of your site, e.g. "/blog"
repository               : "matan-h/matan-h.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "<img src=/android-chrome-192x192.png style='height: 100px;' class='site-icon'></img>" # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
breadcrumbs: true  # disabled by default

words_per_minute         : 200
comments:
  provider               : "giscus" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "giscus", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : "R_kgDOKjgHQw" # Shown during giscus setup at https://giscus.app
    category_name        : "Comments" # Full text name of the category
    category_id          : "DIC_kwDOKjgHQ84CaZ9w" # Shown during giscus setup at https://giscus.app
    discussion_term      : "og:title" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : '1' # '1' for enabled (default), '0' for disabled
    input-position       : 'top'
    # theme                : 'https://matan-h.github.io/assets/css/custom_giscus.css' # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme" # TODO: custom css
    theme                : 'light_tritanopia' # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme" # TODO: custom css
    crossorigin: 'anonymous'
    emit_metadata         : '1'
    strict               : # 1 for enabled, 0 for disabled (default)
    input_position       : 'top' # "top", "bottom" # The comment input box will be placed above or below the comments
    lang                 : # "en" (default)
    lazy                 : true # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.

reCaptcha:
  siteKey                : 
  secret                 :

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr # lunr (default), algolia
algolia:
  application_id         :  # YOUR_APPLICATION_ID
  index_name             :  # YOUR_INDEX_NAME
  search_only_api_key    :  # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
  files_to_exclude:
# SEO Related
google_site_verification :  # Replace this with your ID, or delete
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "matanh_dev"
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/matanh_dev"

# Analytics
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : # Replace this with your ID, or delete
    anonymize_ip         : true


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : # "/assets/images/matan-h.jpg"
  bio              : "Creating *cool* python libraries, interested in *rust* , in cyber*security*, and working with electron"
  location         : # "127.0.0.1"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matan-h"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/12269724/matan-h"
    - label: "Fosstodon"
      icon: "fab fa-fw fa-brands fa-mastodon"
      url: "https://fosstodon.org/@matan_h"



# Site Footer
footer:
  links:
    - label: "Fosstodon"
      icon: "fab fa-fw fa-brands fa-mastodon"
      url: "https://fosstodon.org/@matan_h"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matan-h"
    - label: "buy me a coffee"
      icon: "fab fa fa-coffee"
      url: "https://www.buymeacoffee.com/matanh"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
# collections:


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # assets
  # - scope:
  #      path: "assets/*"
  #   values:
  #     sitemap: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
